[package]
name = "dhke"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
num-bigint = { version = "0.4", features = ["rand"] }
rand = "0.8"
clap = { version = "3.1.5" }
